function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  })[character]);
}

function themeClass(theme) {
  return theme === 'dark' ? 'theme-dark' : 'theme-light';
}

const sharedThemeCss = `
  body.theme-light { --vscode-foreground:#3f4650; --vscode-descriptionForeground:#6d7480; --vscode-editor-background:#f8f9fb; --vscode-textCodeBlock-background:#eef0f4; --vscode-widget-border:#d8dce3; --vscode-button-background:#4d78d2; --vscode-button-foreground:#fff; --vscode-testing-iconPassed:#388a4b; --vscode-diffEditor-insertedTextBackground:#e4f2e7; --vscode-testing-iconFailed:#c84d43; --vscode-diffEditor-removedTextBackground:#f7e4e2; --vscode-focusBorder:#4d78d2; color-scheme:light; }
  body.theme-dark { color-scheme:dark; }
`;

function renderSafeHttpRequestHtml(detail, nonce, theme = 'light') {
  const rows = (items, empty = 'Aucune donnée') => items?.length
    ? `<pre>${escapeHtml(items.map((item) => `${item.name}: ${item.value}`).join('\n'))}</pre>`
    : `<p class="muted">${empty}</p>`;
  const findings = (detail.linkedFindings || []).map((finding) => `<div class="finding"><strong>${escapeHtml(finding.severity)}</strong><span>${escapeHtml(finding.title)}</span><small>${escapeHtml(finding.source)}</small><button data-finding-index="${finding.index}">Ouvrir →</button></div>`).join('') || '<p class="muted">Aucun finding lié.</p>';
  return `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style nonce="${nonce}">
  body{color:var(--vscode-foreground);background:var(--vscode-editor-background);font-family:var(--vscode-font-family);padding:18px;max-width:1050px;margin:auto}${sharedThemeCss}h1{font-size:22px;overflow-wrap:anywhere}h2{font-size:14px;margin-top:22px}.grid{display:grid;grid-template-columns:150px minmax(0,1fr);gap:7px 12px;border:1px solid var(--vscode-widget-border);border-radius:6px;padding:12px}.label,.muted,small{color:var(--vscode-descriptionForeground)}code,pre{background:var(--vscode-textCodeBlock-background);padding:7px;border-radius:4px;white-space:pre-wrap;overflow-wrap:anywhere;max-height:280px;overflow:auto}.finding{display:grid;grid-template-columns:60px minmax(0,1fr) 90px auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--vscode-widget-border)}button{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:0;border-radius:3px;padding:6px 9px;cursor:pointer}.back{margin-bottom:10px}.actions{display:flex;flex-wrap:wrap;gap:7px;margin:18px 0}@media(max-width:650px){body{padding:12px}.grid,.finding{grid-template-columns:1fr}.label{font-weight:700}}
  </style></head><body class="${themeClass(theme)}"><button id="back" class="back">← Retour à Dynamic Security</button><h1>${escapeHtml(detail.method)} ${escapeHtml(detail.path || detail.url)}</h1><div class="grid"><span class="label">URL</span><code>${escapeHtml(detail.url)}</code><span class="label">Horodatage</span><span>${escapeHtml(detail.timestamp || 'Non disponible')}</span><span class="label">Source</span><span>${escapeHtml(detail.source)}</span><span class="label">Durée</span><span>${escapeHtml(detail.duration)}</span></div><h2>En-têtes de la requête</h2>${rows(detail.headers)}<h2>Paramètres</h2>${rows((detail.parameters || []).map((item) => ({name:`${item.location} · ${item.name}`,value:item.value})))}<h2>Corps assaini de la requête</h2><pre>${escapeHtml(detail.requestBody || 'Aucun corps')}</pre><h2>Réponse</h2><div class="grid"><span class="label">Statut</span><span>${escapeHtml(detail.statusCode || '—')}</span><span class="label">Type</span><span>${escapeHtml(detail.responseType)}</span></div><h2>En-têtes de réponse</h2>${rows(detail.responseHeaders)}<h2>Aperçu sécurisé</h2><pre>${escapeHtml(detail.responsePreview || 'Aucun corps')}</pre><h2>Findings liés</h2>${findings}<pre id="safe-request" hidden>${escapeHtml(detail.safeRequest || '')}</pre><div class="actions"><button id="copy">Copier la requête assainie</button><button id="replay">Rejouer la requête</button></div><script nonce="${nonce}">const vscode=acquireVsCodeApi();document.getElementById('back').addEventListener('click',()=>vscode.postMessage({type:'back'}));document.querySelectorAll('[data-finding-index]').forEach(b=>b.addEventListener('click',()=>vscode.postMessage({type:'finding',index:Number(b.dataset.findingIndex)})));document.getElementById('copy').addEventListener('click',()=>navigator.clipboard.writeText(document.getElementById('safe-request').textContent));document.getElementById('replay').addEventListener('click',()=>vscode.postMessage({type:'replay'}));</script></body></html>`;
}

function renderHttpReplayHtml(scenario, replay, nonce, linkedFinding, theme = 'light') {
  const comparison = replay.comparison || {};
  const verdict = comparison.statusChanged || comparison.bodyChanged ? 'Réponse modifiée' : 'Réponse stable';
  const verdictClass = comparison.statusChanged || comparison.bodyChanged ? 'changed' : 'stable';
  const duration = Number.isFinite(replay.durationMs) ? `${replay.durationMs} ms` : 'non disponible';
  const linkedAfter = Number.isInteger(replay.linkedFindingsAfter) ? replay.linkedFindingsAfter : 'non évalué — aucun nouveau scan';
  return `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style nonce="${nonce}">
  body{color:var(--vscode-foreground);background:var(--vscode-editor-background);font-family:var(--vscode-font-family);padding:18px;max-width:980px;margin:auto}${sharedThemeCss}h1{font-size:22px}h2{font-size:14px;margin-top:23px}.verdict{display:inline-block;border-radius:999px;padding:5px 10px;font-weight:700}.stable{color:var(--vscode-testing-iconPassed);background:var(--vscode-diffEditor-insertedTextBackground)}.changed{color:var(--vscode-testing-iconFailed);background:var(--vscode-diffEditor-removedTextBackground)}.grid{display:grid;grid-template-columns:170px 1fr;gap:8px 12px;border:1px solid var(--vscode-widget-border);border-radius:7px;padding:12px}.label{color:var(--vscode-descriptionForeground)}code,pre{background:var(--vscode-textCodeBlock-background);border-radius:4px;padding:5px;white-space:pre-wrap;overflow-wrap:anywhere;max-height:240px;overflow:auto}.notice{color:var(--vscode-descriptionForeground);border-left:2px solid var(--vscode-focusBorder);padding-left:9px;line-height:1.45}button{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:0;border-radius:3px;padding:6px 9px;cursor:pointer;margin-bottom:10px}@media(max-width:520px){body{padding:12px}.grid{grid-template-columns:1fr}.label{margin-top:5px;font-weight:700}}
  </style></head><body class="${themeClass(theme)}"><button id="back">← Retour à Dynamic Security</button><h1>${escapeHtml(scenario.name)}</h1><p><span class="verdict ${verdictClass}">${verdict}</span></p>${linkedFinding ? `<p>Preuve liée à la correction : <strong>${escapeHtml(linkedFinding.title)}</strong> <small>(${escapeHtml(linkedFinding.tool)} · statut ${escapeHtml(linkedFinding.triageStatus)})</small></p>` : ''}<h2>Requête rejouée</h2><div class="grid"><div class="label">Méthode</div><div><code>${escapeHtml(scenario.request.method)}</code></div><div class="label">URL</div><div><code>${escapeHtml(scenario.request.url)}</code></div><div class="label">Source</div><div>${escapeHtml(scenario.source)}</div><div class="label">En-têtes masqués</div><div>${escapeHtml((scenario.request.sensitive_headers || []).join(', ') || 'aucun')}</div></div><h2>Comparaison</h2><div class="grid"><div class="label">Statut original</div><div>${escapeHtml(comparison.originalStatusCode || 'inconnu')}</div><div class="label">Statut replay</div><div>${escapeHtml(replay.statusCode)}</div><div class="label">Statut modifié</div><div>${comparison.statusChanged ? 'oui' : 'non'}</div><div class="label">Corps modifié</div><div>${comparison.bodyChanged ? 'oui' : 'non'}</div><div class="label">Réponse modifiée</div><div>${comparison.statusChanged || comparison.bodyChanged ? 'oui' : 'non'}</div><div class="label">Durée</div><div>${escapeHtml(duration)}</div><div class="label">Findings liés avant</div><div>${escapeHtml(replay.linkedFindingsBefore ?? 'non disponible')}</div><div class="label">Findings liés après</div><div>${escapeHtml(linkedAfter)}</div></div><p class="notice"><small>Le statut HTTP et la stabilité de la réponse ne prouvent pas à eux seuls qu’une vulnérabilité est corrigée. Une validation par scan reste nécessaire.</small></p><h2>Réponse du replay</h2><pre>${escapeHtml(replay.body)}</pre><script nonce="${nonce}">const vscode=acquireVsCodeApi();document.getElementById('back').addEventListener('click',()=>vscode.postMessage({type:'back'}));</script></body></html>`;
}

module.exports = { escapeHtml, renderHttpReplayHtml, renderSafeHttpRequestHtml };
